### ISSUE TITLE
Performance is a bit heavy

### ISSUE THREAD

**Issue by tazsingh** [bjtrounson/expo-stripe-gl#1]
Hey there,

Thanks a bunch for this library! It's absolutely wonderful, and I'm enjoying using it as the centrepiece for our upcoming redesign ☺️ 

However, I thought to file an issue for what I'm seeing related to Performance. We're using this on the Web at the moment, and it's about 2x as heavy to render as Stripe's effect by looking at my GPU's Core Clock speed of both using Chrome

Do you have any guidance or tips on something that we can do on our end to improve performance? For example, is there a particular set of options or configuration elsewhere that can improve performance? Or is this something that can be improved in the library itself?

I assume any performance improvements would also benefit other platforms

Much appreciated!

**Comment by bjtrounson** [comment]
Hey,

I'm probably not the best person for this issue since I didn't write any of the code and I'm not really a 3D guy but I did do some of the research when the company I was working at were creating the library so I have some knowledge.

I have had at little look into performance on my machine and I'm only see a 5% - 7% increase in usage on the GPU with the clocks speed staying similar on both. I'm running on a Linux machine using Brave with a Intel iGPU so it could be hardware related but I think unlikely.

If I were to guess at what the problem might be because of the different GL layers this library uses compared to the stripe site. The stripe site uses a minigl library that is pretty compacted and focused on just WebGL, I'm assuming they use that so they get quick content paints and page load times. This library uses expo-gl which might be more bloated as they have to support multiple platforms. Again I'm not that knowledgeable in t[his area but it could be your project setup, I've created a example project that we used for testing in a new branch ["restructure"](https://github.com/bjtrounson/expo-stripe-gl/tree/restructure) which you could use to test if you are getting the same bad performance. To set it up you will have to do an ```npm pack``` in the root directory and move the *.tgz file to the examples/default directory to get the project going until I get this pushed to main. Only other suggestion is to get in contact with @ethanthorpe-pin who wrote most of the library as he might have a better idea on what might be going on.

I also took some time to add a little documentation and make the structure of the project better, won't be shipping a whole expo project to npm soon anymore lol.
 
# Performance Screenshots
## Stripe Website
Stripe seems to hover around 17% - 20% 
![stripe-gpu-perf](https://user-images.githubusercontent.com/44112581/230667074-8d1acb93-1283-434f-b52d-b9e18e9d5d5a.png)

## Library
The library seems to sit at around 25% pretty constantly but seems to stay at a very similar clock speed compared to stripe.
![library-gpu-perf](https://user-images.githubusercontent.com/44112581/230667115-3b73c3f4-491d-4bab-b645-35c4277a98e1.png)

I'm glad you like library quite surprised anyone would want to use it with no documentation. I don't actually use this library in any projects that I maintain anymore as the company that I created it for I no longer work at. @ethanthorpe-pin I think is still there so again probably the best guy to reach I might be able to get you in contact if needed if he doesn't have any contact details on his profile.

**Comment by tazsingh** [comment]
Thanks! To be honest it wasn't too complicated to just look at the code and figure out how it works 😄

I took a bit of time to compare with the performance of https://github.com/khasty720/stripe-gradient , which is a more web-focused implementation of what appears to be more-or-less similar code under the hood and got similar performance results as this library.

I assume Stripe is doing something on their side that both of these implementations don't quite have.

Either way, I'll close off this issue as I primarily wanted to ask if yourself or @ethanthorpe-pin have any performance-related advice, which you've provided.

Much appreciated for putting this together and sharing it once again!
